marketplace/forms/__init__.py
from marketplace.forms.insert_form import InsertForm

marketplace/forms/insert_form.py
from wtforms import Form, BooleanField, TextField, SelectField, DecimalField, FileField, validators

class InsertForm(Form):
    name = TextField('Item Name', [validators.Length(min=6, max=200), validators.Required()])
    description = TextField('Description', [validators.Length(min=10, max=2000), validators.Required()])
    condition = SelectField('Condition', [validators.Required()], 
    									  choices=[('new', 'New'), 
    											  ('refurb', 'Mfg. Refurbnished'), 
    											  ('u_mint', 'Used - Mint'),
    											  ('u_vg', 'Used - Very good'),
    											  ('u_good', 'Used - Good'),
    											  ('u_fair', 'Used - Fair'),
    											  ('u_bad', 'Used - Bad')])
    price = DecimalField('Price', [validators.Required()]) 
    image = FileField('Image')  #RegEx (shamelessly?) taken from the docs
    accept_terms = BooleanField('I accept Marketplace\'s terms of service', [validators.Required()])

marketplace/routes/auth.py
from flask import Blueprint, jsonify, render_template, json, request, redirect, session, url_for
from marketplace import db, flow, login_required
from marketplace.models import User
from marketplace.routes import home
from oauth2client.client import OAuth2WebServerFlow
from datetime import date, datetime
from flask.ext.restful import reqparse  # Parse through requests
import httplib2
import re

auth = Blueprint('auth', __name__)

# From Density project
CU_EMAIL_REGEX = r"^(?P<uni>[a-z\d]+)@.*(columbia|barnard)\.edu$"


@auth.route("/logout")
def logout():
    session.pop("username", None)
    session["logged_in"] = False
    return redirect(url_for('home.home_page'))


@auth.route("/session_test")
def session_test():
    if "username" in session:
        return session["username"]
    else:
        return "You're not logged in."


@auth.route("/login/google")
def google_login():
    code = request.args.get('code', '')
    error = request.args.get('error', '')
    if code:  # We have a login code
        credentials = flow.step2_exchange(code)
        http = httplib2.Http()
        http = credentials.authorize(http)
        gplus_id = credentials.id_token['sub']
        h, content = http.request('https://www.googleapis.com/plus/v1/people/'
                                  + gplus_id, 'GET')
        data = json.loads(content)
        email = data["emails"][0]["value"]
        return signin(email)
    elif error:  # Google login returned an error; alert the user
        #home.home_page_error("An error occcurred authenticating you.")
        return redirect(url_for('home.home_page'))
    else:  # We just got to the code in the first place
        return redirect(flow.step1_get_authorize_url())


def signin(email):
    """
    Post Google sign in, register as necessary or just return to listings
    """
    matching_users = User.query.filter_by(user_id=email).all()
    matches = len(matching_users)
    if matches == 0:
        return register(email)
    elif matches == 1:
        session["username"] = matching_users[0].user_id
        session["logged_in"] = True
        return redirect(url_for('home.home_page'))
    #home.home_page_error("Error signing in!")
    return redirect(url_for('home.home_page'))


def register(email):
    """
    Register a new user.
    """
    # Catch regex errors
    regex_result = re.match(CU_EMAIL_REGEX, email)
    if not regex_result:
        return redirect(url_for('home.home_page'))
        #home.home_page_error("Please login with a Columbia or Barnard provided email.")
        return

    user = User(email, 0, 0)
    db.session.add(user)
    db.session.commit()

    session["username"] = email
    session["logged_in"] = True

    return redirect(url_for('home.home_page'))
    #home.home_page_error("Welcome to Marketplace!")

marketplace/routes/insert.py
from flask import Blueprint, request, render_template
from marketplace import db, session, login_required
from marketplace.models import Item
from marketplace.forms import InsertForm
from datetime import date, datetime

insert = Blueprint('insert', __name__) # Leave of URL prefix intentionally


@insert.route('/insert/<name>/<description>/<condition>/<image_url>/<float:price>')
@login_required
def insert_item(name, description, condition, image_url, price):
    new_item = Item(session["username"], name, 
        description, condition, image_url, price, 
        date.today(), date.today(), None, 'listed')
    db.session.add(new_item)
    db.session.commit()
    return "Item added with id: " + str(new_item.id)


@insert.route('/sell_item', methods=['GET', 'POST'])
@login_required
def sell_item():
    form = InsertForm(request.form)
    if request.method == 'POST' and form.validate():
        insert_item(form.name.data, form.description.data,
                    form.condition.data, "boo", form.price.data)
        return "Item added"
    return render_template('sell.html', form=form)


@insert.route('/mark_sold/<item_id>/<sold_to>')
@login_required
def mark_sold(item_id, sold_to):
    item = Item.query.filter_by(id=item_id).all()
    if len(item) == 0:
        return "No item found!"
    if item[0].user_id != session["username"]:
        return "You can't mark someone else's item as sold. Bad."
    if item[0].status != "listed":
        return "You can't mark this item as sold. It's in state " + item[0].status + "."
    if sold_to == session["username"]:
        return "You can't sell an item to yourself."
    item[0].status = "sold"
    item[0].sold_to = sold_to
    db.session.commit()
    return "Marked as sold."


@insert.route('/bulk_test')
@login_required
def bulk_test():
    for i in range(100):
        new_item = Item("uni123", "Product name", "Product description", "new"
                        "http://www.dunbartutoring.com/wp-content/themes/thesis/rotator/sample-1.jpg",
                        i, datetime.utcnow(), datetime.utcnow(), None,
                        'listed')
        db.session.add(new_item)
    db.session.commit()
    return "Bulk test complete."

marketplace/templates/__formhelpers.html
<!-- Macro from http://flask.pocoo.org/docs/0.10/patterns/wtforms/ -->

{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

marketplace/templates/base.html
<!DOCTYPE html> 
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]--> 
<html class="no-js" lang="en" > 

<head> 
  {% block head %}{% endblock %}
  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <title>{% block title %}{% endblock %}</title> 

  <!-- If you are using CSS version, only link these 2 files, you may add app.css to use for your overrides if you like. --> 
  <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css')}}"> 
  <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.css')}}"> 

  <!-- If you are using the gem version, you need this only --> 
  <link rel = "stylesheet" type = "text/css" href="{{ url_for('static', filename='css/base.css') }}" >
  <script src="{{ url_for('static', filename='css/modernizr.js')}}"></script> 


<div class="top" style="background-color: #2285c6;">
  <p><font color="white">Marketplace</font></p>

</div>

<div class = "logo">
  <img src = "{{ url_for('static', filename='img/cu.jpg') }}">
</div>

<a class="small button round dropdown" href="#" data-dropdown="drop1" style="background-color:#e0e0e0; margin-left:400px; margin-top:7px;"> <font color="#2285c6">     My Stuff     </font></a>
</pre>
<ul class="f-dropdown" id="drop1">
    <li><a href="/profile">My Profile</a></li>
    <li><a href="/sales">My Sales</a></li>
    <li><a href="/purchases">My Purchases</a></li>
</ul>

<div class = "putton">
  <a href="/public" class="round button small" style="background-color:#e0e0e0; margin-left:200px"> <font color="#2285c6">  Public Forum  </font></a>
</div>

</head> 
<body> 

  <!-- body content here --> 
  {% block body %}{% endblock %}

  <script src="{{ url_for('static', filename='js/vendor/jquery.js')}}"></script> 
  <script src="{{ url_for('static', filename='js/foundation.min.js')}}"></script> 
  <script> 
    $(document).foundation(); 
  </script> 
</body> 
</html>

marketplace/templates/index.html
{% extends "layout.html" %}

{% block head %}
	{{ super() }}

{% endblock %}

{% block body %}
	{{ super() }}
<!-- start slider -->
<div id="da-slider" class="da-slider">
	<div class="da-slide">
		<h2>Welcome to Marketplace</h2>
		<p></p>
		<a href="{{ url_for('home.home_page') }}" class="da-link">Shop Now</a>
		<a href="{{ url_for('insert.sell_item') }}" class="da-link">Sell</a>
	</div>
	<div class="da-img"><img src="../static/images/cart_main.png" alt="image01" /></div>
</div>
{% endblock %}


marketplace/templates/insert_item.html
{% from "__formhelpers.html" import render_field %}
<form method=post action="/sell_item">
  <dl>
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    {{ render_field(form.condition) }}
    {{ render_field(form.price) }}
    {{ render_field(form.image) }}
    {{ render_field(form.accept_terms) }}
  </dl>
  <p><input type="submit" value="Sell it!"></p>
</form>

marketplace/templates/itemList.html
{% extends "layout.html" %}

{% block head %}
	{{ super() }}

{% endblock %}


{% block body %}
	{{ super() }}
<!-- start main -->
<div class="main_bg">
<div class="wrap">	
	<div class="main">
		<!-- start grids_of_3 -->
		<div class="grids_of_3">
			<div class="grid1_of_3">
				<a href="{{ url_for('.details_page') }}">
					<img src="images/pic1.jpg" alt=""/>
					<h3>branded shoes</h3>
					<div class="price">
						<h4>$300<span>indulge</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
			<div class="grid1_of_3">
				<a href="details.html">
					<img src="images/pic2.jpg" alt=""/>
					<h3>branded t-shirts</h3>
					<div class="price">
						<h4>$300<span>indulge</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
			<div class="grid1_of_3">
				<a href="details.html">
					<img src="images/pic3.jpg" alt=""/>
					<h3>branded tees</h3>
					<div class="price">
						<h4>$300<span>indulge</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
			<div class="clear"></div>
		</div>
		<div class="grids_of_3">
			<div class="grid1_of_3">
				<a href="details.html">
					<img src="images/pic4.jpg" alt=""/>
					<h3>branded bags</h3>
					<div class="price">
						<h4>$300<span>indulge</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
			<div class="grid1_of_3">
				<a href="details.html">
					<img src="images/pic5.jpg" alt=""/>
					<h3>ems women bag</h3>
					<div class="price">
						<h4>$300<span>indulge</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
			<div class="grid1_of_3">
				<a href="details.html">
					<img src="images/pic6.jpg" alt=""/>
					<h3>branded cargos</h3>
					<div class="price">
						<h4>$300<span>indulge</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
			<div class="clear"></div>
		</div>	
		<!-- end grids_of_3 -->
	</div>
</div>
</div>	
{% endblock %}

marketplace/templates/item_add_form.html
<html>
<head>

	<link rel="stylesheet" type="text/css" href="bootstrap.css">

	<title>Add items</title>
</head>

<body>

	<form action="" method="post">
		<div>
			<label id="item_name_label" for="item_name">Item Name:</label>
	        <input type="text" id="item_name">
		</div>

		<div>
			<label id="item_description_label" for="item_description">Description:</label>
		    <input type="text" id="item_description">
		</div>

		<div>
			<label id="price_label" for="price">Price:</label>
	        <span>$</span><input type="text" id="price">
	    </div>

		<input type="submit">
	</form>

</body>

</html>

marketplace/templates/layout.html
<!--http://www.cssreset.com/how-to-keep-footer-at-bottom-of-page-with-css/ -->	
<!DOCTYPE HTML>
<head>
    {% block head %}
	<title>Marketplace</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
	<link href="../static/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="../static/js/jquery.min.js"></script>
    {% endblock %}
</head>

<body>
<div class="wrapper">
  	<div class="main_content">
   		{% if error_message is defined %}
	  		<div class="alert-container">
			    <div class="alert">
			        {{ error_message }}
			    </div>
			    <div id="alert-close">
			        &times;
			    </div>
			</div>
		{% endif %}

    	<!-- Page header -->
		<div class="header">
			<div class="logo">
				<a href="{{ url_for('home.home_page') }}">Marketplace </a>
			</div>


			{% if session.logged_in %}
			<div class="login_icon">	
				<a class="btn" href="{{ url_for('auth.logout') }}"> Logout </a>
			</div>

			{% else %}
			<div class="login_icon">	
				<a class="btn" href="{{ url_for('auth.google_login') }}"> Login </a>
			</div>
			{% endif %}


			<!-- Search bar -->
			<div class="h_search">
				<form>
					<input type="text" value="">
					<input type="submit" value="">
				</form>
			</div>

			<div class="clear"></div>
		</div>

		<div class="menu_bar">
			<div class="h_menu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li class="separator">|</li>

					<li><a href="test.html">all</a></li>
					<li class="separator">|</li>

					<li><a href="handbags.html">textbook</a></li>
					<li class="separator">|</li>
					
					<li><a href="accessories.html">price</a></li> 
					<li class="separator">|</li>

					<li><a href="accessories.html">price</a></li> 			
					<li class="separator">|</li>

					<li><a href="accessories.html">price</a></li> 				
				
				</ul>
			</div>
			<div class="clear"></div>

  	{% block body %}
  	{% endblock %}

  	<!-- Start footer -->
	<div class="footer_home">
		 <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
		<!--end scroll_top_btn -->
		<div class="copy">
			<p class="link">&copy;  Made in&nbsp;&nbsp;<a href="https://adicu.com/labs"> ADI Labs</a></p>
		</div>
		<div class="clear"></div>
	</div>

  	{% block scripts %}
  	{% endblock %}
	
	</div>
</div>
</body>

marketplace/templates/login.html
<!DOCTYPE HTML>
<html>
<head>
<title>Marketplace</title>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="google-signin-clientid" content="CLIENT_ID" />
<meta name="google-signin-scope" content="https://www.googleapis.com/auth/plus.login" />
<meta name="google-signin-requestvisibleactions" content="http://schema.org/AddAction" />
<meta name="google-signin-cookiepolicy" content="single_host_origin" />
<meta name="google-signin-callback" content="signinCallback" />

<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
<link href="../static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="../static/js/jquery.min.js"></script>


<!-- start slider -->		
<link href="../static/css/slider.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="../static/js/modernizr.custom.28468.js"></script>
<script type="text/javascript" src="../static/js/jquery.cslider.js"></script>
<script type="text/javascript">
	$(function() {
		$('#da-slider').cslider();
	});
</script>
	<!-- Owl Carousel Assets -->
	<link href="css/owl.carousel.css" rel="stylesheet">
	     <!-- Owl Carousel Assets -->
	    <!-- Prettify -->
	    <script src="../static/js/owl.carousel.js"></script>
	        <script>
	    $(document).ready(function() {
	
	      $("#owl-demo").owlCarousel({
	        items : 4,
	        lazyLoad : true,
	        autoPlay : true,
	        navigation : true,
		    navigationText : ["",""],
		    rewindNav : false,
		    scrollPerPage : false,
		    pagination : false,
			paginationNumbers: false,
	      });
	
	    });
	    </script>
	   <!-- //Owl Carousel Assets -->
	<!-- start top_js_button -->
	<script type="text/javascript" src="../static/js/move-top.js"></script>
	<script type="text/javascript" src="../static/js/easing.js"></script>
    <script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
			});
		});
	</script>
		<!-- Owl Carousel Assets -->
		<link href="css/owl.carousel.css" rel="stylesheet">
		     <!-- Owl Carousel Assets -->
		    <!-- Prettify -->
		    <script src="../static/js/owl.carousel.js"></script>
		        <script>
		    $(document).ready(function() {
		
		      $("#owl-demo").owlCarousel({
		        items : 4,
		        lazyLoad : true,
		        autoPlay : true,
		        navigation : true,
			    navigationText : ["",""],
			    rewindNav : false,
			    scrollPerPage : false,
			    pagination : false,
    			paginationNumbers: false,
		      });
		
		    });
		    </script>
		   <!-- //Owl Carousel Assets -->
		<!-- start top_js_button -->
		<script type="text/javascript" src="../static/js/move-top.js"></script>
		<script type="text/javascript" src="../static/js/easing.js"></script>
		   <script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){		
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
					});
				});
			</script>
		<script src="https://apis.google.com/js/client:platform.js?onload=render" async defer>
			/* Executed when the APIs finish loading */
			function render() {

			  // Additional params
			  var additionalParams = {
			    'theme' : 'dark'
			  };

			  gapi.signin.render('myButton', additionalParams);
			}
			</script>
</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<a href="{{ url_for('.home_page') }}">Marketplace </a>
		</div>
		<div class="login_icon">	
			<a class="btn" href="#">Login</a>
		</div>
		<div class="h_search">
    		<form>
    			<input type="text" value="">
    			<input type="submit" value="">
    		</form>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>
<div class="header_btm">
<div class="wrap">
	<div class="header_sub">
		<div class="h_menu">
			<ul>
				<!-- use this for indentation -->
				<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
				<li class="active"><a href="index.html">Home</a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<li><a href="{{ url_for('.list_page') }}">all</a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<li><a href="handbags.html">textbook</a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<li><a href="accessories.html">price</a></li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<li><a href="wallets.html">newest</a></li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				
				<li><a href="contact.html">Contact us</a></li>
			</ul>
		</div>
		<div class="top-nav">
	          <nav class="nav">	        	
	    	    <a href="#" id="w3-menu-trigger"> </a>
	                  <ul class="nav-list" style="">
	            	        <li class="nav-item"><a class="active" href="index.html">Home</a></li>
							<li class="nav-item"><a href="sale.html">Sale</a></li>
							<li class="nav-item"><a href="handbags.html">Handbags</a></li>
							<li class="nav-item"><a href="accessories.html">Accessories</a></li>
							<li class="nav-item"><a href="shoes.html">Shoes</a></li>
							<li class="nav-item"><a href="service.html">Services</a></li>
							<li class="nav-item"><a href="contact.html">Contact</a></li>
	                 </ul>
	           </nav>
	             <div class="search_box">
				<form>
				   <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
			    </form>
			</div>
	          <div class="clear"> </div>
	          <script src="../static/js/responsive.menu.js"></script>
         </div>		  
	<div class="clear"></div>
</div>
</div>
</div>



<div class="main_bg">
<div class="wrap">	
<div class="main">
	 	 <div class="contact">				
					
				  <div class="contact-form">
			 	  	 	<h2>Login</h2>
			 	 	    <form method="post" onclick = "login()">
					    	
						   		<span><input type="submit" class="" value="Sign up with Google"></span>
						   		<script>
					      function login() {
					          var params = {
					              'callback': signinCallback,
					              'clientid': '18084506948-mgmomgbk9ciau6teih4jclb0anp1ah2h.apps.googleusercontent.com',
					              'scope': 'https://www.googleapis.com/auth/plus.profile.emails.read',
					              'requestvisibleactions': 'http://schema.org/AddAction',
					              'cookiepolicy': 'single_host_origin'
					          };
					          gapi.auth.signIn(params);
					      }
					      function signinCallback(authResult) {
					          if (authResult['status']['signed_in']) {
					          // Update the app to reflect a signed in user
					          // Hide the sign-in button now that the user is authorized, for example:
					          document.location.href = '/auth?code=' + authResult.code
					        }
					      }
					    </script>
					    </form>
				    </div>
  				<div class="clear"></div>		
			  </div>
		</div>
</div>
</div>		


<!---
<div class="main_bg">
<div class="wrap">	
<div class="main">
	 	 <div class="contact">				
					
				  <div class="contact-form">
			 	  	 	<h2>Login</h2>

			 	  	 	<button id='signinButton' type = "submit" onclick='login()' style="margin-bottom: 1em;">
					        Get access
					    </button>
					    <script>
					      function login() {
					          var params = {
					              'callback': signinCallback,
					              'clientid': '859795907220-57lf7t8m19a1i3huaogqg546u5efjk8j.apps.googleusercontent.com',
					              'scope': 'https://www.googleapis.com/auth/plus.profile.emails.read',
					              'requestvisibleactions': 'http://schema.org/AddAction',
					              'cookiepolicy': 'single_host_origin'
					          };
					          gapi.auth.signIn(params);
					      }
					      function signinCallback(authResult) {
					          if (authResult['status']['signed_in']) {
					          // Update the app to reflect a signed in user
					          // Hide the sign-in button now that the user is authorized, for example:
					          document.location.href = '/auth?code=' + authResult.code
					        }
					      }
					    </script>
				    </div>
  				<div class="clear"></div>		
			  </div>
		</div>
</div>
</div>

//--->







<!-- start footer -->
<div class="footer_home">
<div class="wrap">
	<!-- scroll_top_btn -->
    <script type="text/javascript">
		$(document).ready(function() {
		
			var defaults = {
	  			containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
	 		};
			
			
			$().UItoTop({ easingType: 'easeOutQuart' });
			
		});
	</script>
	 <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
	<!--end scroll_top_btn -->
	<div class="copy">
		<p class="link">&copy;  Made in&nbsp;&nbsp;<a href="https://adicu.com/labs"> ADI Labs</a></p>
	</div>
	<div class="clear"></div>
</div>
</div>
</body>
</html>

marketplace/templates/primary_user_interface.html
<html>
<head>
	<title>
		CU - Marketplace
	</title>

	<link rel="stylesheet" type="text/css" href="static/css/primary_UI_styling.css">

</head>

<body>

	<div id="header">
		Rando header text
	</div>

	<div id="center-section">
		<div id="search_wrapper">
			<form>
				<input type="text" placeholder="Search">
				<input type="submit">
			</form>
		</div>

		<div id="query_results">
			<div id="book_container">
				<div id="book_image_wrapper">
					<img id="book_image" src="static/images/samplebook.jpg">
				</div>
				<div id="book_center_text">
					{% for book in book_center_text %}
						<div id="book_title">
							This is the title of the book
						</div>
						<div id="book_author">
							J.K. Rowling
						</div>
						<div id="book_ISBN">
							ISBN: 1234567890
						</div>
					{% endfor %}
				</div>
				<div id="book_button_wrapper">
					<input type = "button" value="Check Prices">
				</div>

			</div>
		</div>

	</div>

</body>

</html>

marketplace/templates/results.html
{% extends 'base.html' %}

{% block title %}
Marketplace by ADICU
{% endblock %}


{% block body %}
<div class="row">
  <div class="medium-9 medium-centered columns">
    <div class="panel" style="margin-left:26rem; margin-right:-26rem; margin-top:-7rem;">
        {%for item in data%}
	        <h1>{{item.item_name}}           {{item.price}}</h1>
	        <h3>{{item.user_id}}</h3>
	        <br>
	        <p>{{item.item_description}}</p>
	    {%endfor%}
	</div>
  </div>
</div>
{% endblock %}

marketplace/templates/sell.html
{% extends "layout.html" %}

{% block head %}
	{{ super() }}

{% endblock %}


{% block body %}
	{{ super() }}

{% from "__formhelpers.html" import render_field %}

<form method="post" action="/sell_item" class="basic-grey">
  <dl>
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    {{ render_field(form.condition) }}
    {{ render_field(form.price) }}
    {{ render_field(form.image) }}
    {{ render_field(form.accept_terms) }}
  </dl>
  <p><input type="submit" value="Sell it!"></p>
</form>

{% endblock %}